server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cuscutae?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
logging:
  level:
    com.spearmint.admin: info
jwt:
  header: Authorization
  secret: dk-like-syc
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml